apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: demo-guestbook-app
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-guestbook-app
      tier: front-end
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        app: demo-guestbook-app
        tier: front-end
    spec:
      containers:
        - name: guestbook
          image: kubernetes/guestbook:v2
          ports:
            - containerPort: 80
