apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-guestbook-app
    tier: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-guestbook-app
      tier: back-end
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-guestbook-app
        tier: back-end
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379